version: '3.8'

services:
  app:
    build: .
    container_name: bnpl-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - TZ=UTC
      - JAVA_OPTS=-Duser.timezone=UTC
    volumes:
      - ./logs:/app/logs
    networks:
      - bnpl-network
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: bnpl-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # PostgreSQL performance tuning
      - POSTGRES_SHARED_BUFFERS=${POSTGRES_SHARED_BUFFERS}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE}
      - POSTGRES_WORK_MEM=${POSTGRES_WORK_MEM}
      - POSTGRES_MAINTENANCE_WORK_MEM=${POSTGRES_MAINTENANCE_WORK_MEM}
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS}
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bnpl-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bnpl-network:
    driver: bridge