version: '3.8'

services:
  app:
    build: .
    container_name: bnpl-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bnpl
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - JWT_SECRET=asecuresecretkeywithlength32charactr
      - JWT_EXPIRATION=86400
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - TZ=UTC
      - JAVA_OPTS=-Duser.timezone=UTC
    volumes:
      - ./logs:/app/logs
    networks:
      - bnpl-network
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: bnpl-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bnpl
      # PostgreSQL performance tuning
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=768MB
      - POSTGRES_WORK_MEM=8MB
      - POSTGRES_MAINTENANCE_WORK_MEM=64MB
      - POSTGRES_MAX_CONNECTIONS=100
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/init:/docker-entrypoint-initdb.d
    networks:
      - bnpl-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bnpl-network:
    driver: bridge